apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devsecops-staging

resources:
  - ../../base

namePrefix: staging-

commonAnnotations:
  environment: staging
  security-tier: pre-production-dast
