apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devsecops-prod

resources:
  - ../../base

namePrefix: prod-

replicas:
  - name: orders-service
    count: 2
  - name: notification-service
    count: 2
  - name: web
    count: 2
  - name: dashboard
    count: 2

commonAnnotations:
  environment: production
  compliance: high-availability
